<?php

declare(strict_types=1);

/**
 * Rebuild container for addition of Discourse config and permalink resolver.
 */
function omnipedia_discourse_update_101001(): void {

  \Drupal::service('kernel')->invalidateContainer();

}

/**
 * Invalidate the Discourse SSO config cache tag for menu link refactor.
 */
function omnipedia_discourse_update_101002(): void {

  \Drupal::service('cache_tags.invalidator')->invalidateTags([
    'config:discourse_sso.settings',
  ]);

}

/**
 * Rebuild container and router for Talk local task Discourse direct links.
 */
function omnipedia_discourse_update_101003(): void {

  \Drupal::service('kernel')->invalidateContainer();

  \Drupal::service('router.builder')->rebuild();

}
